/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RifasIndexRouteImport } from './routes/rifas.index'
import { Route as RifasIdRouteImport } from './routes/rifas.$id'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RifasIndexRoute = RifasIndexRouteImport.update({
  id: '/rifas/',
  path: '/rifas/',
  getParentRoute: () => rootRouteImport,
} as any)
const RifasIdRoute = RifasIdRouteImport.update({
  id: '/rifas/$id',
  path: '/rifas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comunidade': typeof ComunidadeRoute
  '/suporte': typeof SuporteRoute
  '/rifas/$id': typeof RifasIdRoute
  '/rifas/': typeof RifasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comunidade': typeof ComunidadeRoute
  '/suporte': typeof SuporteRoute
  '/rifas/$id': typeof RifasIdRoute
  '/rifas': typeof RifasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comunidade': typeof ComunidadeRoute
  '/suporte': typeof SuporteRoute
  '/rifas/$id': typeof RifasIdRoute
  '/rifas/': typeof RifasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comunidade' | '/suporte' | '/rifas/$id' | '/rifas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comunidade' | '/suporte' | '/rifas/$id' | '/rifas'
  id: '__root__' | '/' | '/comunidade' | '/suporte' | '/rifas/$id' | '/rifas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComunidadeRoute: typeof ComunidadeRoute
  SuporteRoute: typeof SuporteRoute
  RifasIdRoute: typeof RifasIdRoute
  RifasIndexRoute: typeof RifasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rifas/': {
      id: '/rifas/'
      path: '/rifas'
      fullPath: '/rifas/'
      preLoaderRoute: typeof RifasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rifas/$id': {
      id: '/rifas/$id'
      path: '/rifas/$id'
      fullPath: '/rifas/$id'
      preLoaderRoute: typeof RifasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComunidadeRoute: ComunidadeRoute,
  SuporteRoute: SuporteRoute,
  RifasIdRoute: RifasIdRoute,
  RifasIndexRoute: RifasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
